# Generated by Django 5.1.5 on 2026-06-05 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('checker', '0002_remove_attempt_image_url_attempt_image_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='anonymous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.anonymoussession'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anonymous_session__isnull', True), ('user__isnull', False)), models.Q(('anonymous_session__isnull', False), ('user__isnull', True)), _connector='OR'), name='attempt_owner_xor'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='anonymous_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.anonymoussession'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anonymous_session__isnull', True), ('user__isnull', False)), models.Q(('anonymous_session__isnull', False), ('user__isnull', True)), _connector='OR'), name='userstats_owner_xor'),
        ),
    ]
