# Generated by Django 5.1.15 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_add_word_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='symbol_type',
            field=models.CharField(choices=[('letter', 'Letter'), ('grouping', 'Grouping')], default='letter', max_length=8),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='letter',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
