# Generated by Django 5.1.15 on 2026-06-06 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_symbol_symbol_type_alter_attempt_predicted_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOutline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meaning', models.CharField(max_length=100)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_outlines', to='checker.symbol')),
            ],
            options={
                'ordering': ['meaning'],
                'unique_together': {('symbol', 'meaning')},
            },
        ),
    ]
