# Generated by Django 5.1.15 on 2026-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_specialoutline'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='teeline_skeleton',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
