# Generated by Django 5.1.15 on 2026-06-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_word_teeline_skeleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='teeline_skeleton',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
