# Generated by Django 5.1.15 on 2026-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_alter_word_teeline_skeleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
