# Generated by Django 5.1.15 on 2026-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('memory_used_mb', models.FloatField()),
                ('memory_total_mb', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('disk_used_gb', models.FloatField()),
                ('disk_total_gb', models.FloatField()),
                ('process_uptime_seconds', models.FloatField()),
                ('db_size_mb', models.FloatField()),
                ('db_connections', models.IntegerField()),
                ('table_stats', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
